import {DndTextFeatPrerequisiteStoreState} from '@root-store/dnd-text-feat-prerequisite-store';
import {DndSpellSubschoolStoreState} from '@root-store/dnd-spell-subschool-store';
import {DndSpellSchoolStoreState} from '@root-store/dnd-spell-school-store';
import {DndSpellDomainLevelStoreState} from '@root-store/dnd-spell-domain-level-store';
import {DndSpellDescriptorsStoreState} from '@root-store/dnd-spell-descriptors-store';
import {DndSpellDescriptorStoreState} from '@root-store/dnd-spell-descriptor-store';
import {DndSpellClassLevelStoreState} from '@root-store/dnd-spell-class-level-store';
import {DndSpellStoreState} from '@root-store/dnd-spell-store';
import {DndSpecialFeatPrerequisiteStoreState} from '@root-store/dnd-special-feat-prerequisite-store';
import {DndSkillVariantStoreState} from '@root-store/dnd-skill-variant-store';
import {DndSkillStoreState} from '@root-store/dnd-skill-store';
import {DndRulesConditionStoreState} from '@root-store/dnd-rules-condition-store';
import {DndRulebookStoreState} from '@root-store/dnd-rulebook-store';
import {DndRaceTypeStoreState} from '@root-store/dnd-race-type-store';
import {DndRaceSpeedTypeStoreState} from '@root-store/dnd-race-speed-type-store';
import {DndRaceSpeedStoreState} from '@root-store/dnd-race-speed-store';
import {DndRaceSizeStoreState} from '@root-store/dnd-race-size-store';
import {DndRaceFavoredCharacterClassStoreState} from '@root-store/dnd-race-favored-character-class-store';
import {DndRaceBonusLanguageStoreState} from '@root-store/dnd-race-bonus-language-store';
import {DndRaceAutomaticLanguageStoreState} from '@root-store/dnd-race-automatic-language-store';
import {DndRaceStoreState} from '@root-store/dnd-race-store';
import {DndLanguageStoreState} from '@root-store/dnd-language-store';
import {DndFeatSpecialFeatPrerequisiteStoreState} from '@root-store/dnd-feat-special-feat-prerequisite-store';
import {DndFeatRequiresSkillStoreState} from '@root-store/dnd-feat-requires-skill-store';
import {DndFeatRequiresFeatStoreState} from '@root-store/dnd-feat-requires-feat-store';
import {DndFeatFeatCategoriesStoreState} from '@root-store/dnd-feat-feat-categories-store';
import {DndFeatCategoryStoreState} from '@root-store/dnd-feat-category-store';
import {DndFeatStoreState} from '@root-store/dnd-feat-store';
import {DndEditionStoreState} from '@root-store/dnd-edition-store';
import {DndDomainStoreState} from '@root-store/dnd-domain-store';
import {DndCharacterClassVariantRequiresSkillStoreState} from '@root-store/dnd-character-class-variant-requires-skill-store';
import {DndCharacterClassVariantRequiresRaceStoreState} from '@root-store/dnd-character-class-variant-requires-race-store';
import {DndCharacterClassVariantRequiresFeatStoreState} from '@root-store/dnd-character-class-variant-requires-feat-store';
import {DndCharacterClassVariantClassSkillStoreState} from '@root-store/dnd-character-class-variant-class-skill-store';
import {DndCharacterClassVariantStoreState} from '@root-store/dnd-character-class-variant-store';
import {DndCharacterClassStoreState} from '@root-store/dnd-character-class-store';
import {InfoStoreState} from '@root-store/info-store';
import {PgStoreState} from '@root-store/pg-store';
import {SpellsInventoryStoreState} from '@root-store/spells-inventory-store';
import {SpellStoreState} from '@root-store/spell-store';
import {SlideMenuStoreState} from '@root-store/slide-menu-store';
import {AuthStoreState} from '@root-store/auth-store';

export interface State {
dnd_text_feat_prerequisite:DndTextFeatPrerequisiteStoreState.State;
dnd_spell_subschool:DndSpellSubschoolStoreState.State;
dnd_spell_school:DndSpellSchoolStoreState.State;
dnd_spell_domain_level:DndSpellDomainLevelStoreState.State;
dnd_spell_descriptors:DndSpellDescriptorsStoreState.State;
dnd_spell_descriptor:DndSpellDescriptorStoreState.State;
dnd_spell_class_level:DndSpellClassLevelStoreState.State;
dnd_spell:DndSpellStoreState.State;
dnd_special_feat_prerequisite:DndSpecialFeatPrerequisiteStoreState.State;
dnd_skill_variant:DndSkillVariantStoreState.State;
dnd_skill:DndSkillStoreState.State;
dnd_rules_condition:DndRulesConditionStoreState.State;
dnd_rulebook:DndRulebookStoreState.State;
dnd_race_type:DndRaceTypeStoreState.State;
dnd_race_speed_type:DndRaceSpeedTypeStoreState.State;
dnd_race_speed:DndRaceSpeedStoreState.State;
dnd_race_size:DndRaceSizeStoreState.State;
dnd_race_favored_character_class:DndRaceFavoredCharacterClassStoreState.State;
dnd_race_bonus_language:DndRaceBonusLanguageStoreState.State;
dnd_race_automatic_language:DndRaceAutomaticLanguageStoreState.State;
dnd_race:DndRaceStoreState.State;
dnd_language:DndLanguageStoreState.State;
dnd_feat_special_feat_prerequisite:DndFeatSpecialFeatPrerequisiteStoreState.State;
dnd_feat_requires_skill:DndFeatRequiresSkillStoreState.State;
dnd_feat_requires_feat:DndFeatRequiresFeatStoreState.State;
dnd_feat_feat_categories:DndFeatFeatCategoriesStoreState.State;
dnd_feat_category:DndFeatCategoryStoreState.State;
dnd_feat:DndFeatStoreState.State;
dnd_edition:DndEditionStoreState.State;
dnd_domain:DndDomainStoreState.State;
dnd_character_class_variant_requires_skill:DndCharacterClassVariantRequiresSkillStoreState.State;
dnd_character_class_variant_requires_race:DndCharacterClassVariantRequiresRaceStoreState.State;
dnd_character_class_variant_requires_feat:DndCharacterClassVariantRequiresFeatStoreState.State;
dnd_character_class_variant_class_skill:DndCharacterClassVariantClassSkillStoreState.State;
dnd_character_class_variant:DndCharacterClassVariantStoreState.State;
dnd_character_class:DndCharacterClassStoreState.State;
  info: InfoStoreState.State;
  pg: PgStoreState.State;
  spells_inventory: SpellsInventoryStoreState.State;
  auth: AuthStoreState.State;
  spell: SpellStoreState.State;
  slide_menu: SlideMenuStoreState.State;
}
